-- Connie: give the backend a narrow role and a programmatic access token (PAT).
-- Run as ACCOUNTADMIN after 01-03. The last statement prints the token ONCE:
-- copy token_secret into backend/.env as SNOWFLAKE_PAT.
USE ROLE ACCOUNTADMIN;
SET me = CURRENT_USER();

-- A role that can only do what the backend needs.
CREATE ROLE IF NOT EXISTS CONNIE_APP;
GRANT USAGE ON WAREHOUSE CONNIE_WH TO ROLE CONNIE_APP;
GRANT USAGE ON DATABASE CONNIE TO ROLE CONNIE_APP;
GRANT USAGE ON SCHEMA CONNIE.APP TO ROLE CONNIE_APP;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA CONNIE.APP TO ROLE CONNIE_APP;
GRANT USAGE ON CORTEX SEARCH SERVICE CONNIE.APP.CONNIE_HISTORY_SEARCH TO ROLE CONNIE_APP;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CONNIE_APP;
GRANT ROLE CONNIE_APP TO USER IDENTIFIER($me);

-- PATs require a network policy by default. For a hackathon laptop whose IP
-- changes, relax that for PATs only (other login methods are unaffected).
CREATE AUTHENTICATION POLICY IF NOT EXISTS CONNIE.APP.CONNIE_PAT_POLICY
  PAT_POLICY = (NETWORK_POLICY_EVALUATION = ENFORCED_NOT_REQUIRED);
ALTER USER IDENTIFIER($me) SET AUTHENTICATION POLICY CONNIE.APP.CONNIE_PAT_POLICY;

-- The token. Scoped to CONNIE_APP, expires after the hackathon.
ALTER USER IDENTIFIER($me) ADD PROGRAMMATIC ACCESS TOKEN CONNIE_BACKEND
  ROLE_RESTRICTION = 'CONNIE_APP'
  DAYS_TO_EXPIRY = 30
  COMMENT = 'Connie backend (ShellHacks 2026)';
